# Generated by Django 5.0.1 on 2024-01-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyndata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomdata', models.JSONField()),
            ],
        ),
    ]
